### ISSUE TITLE
A pdf version 

### ISSUE THREAD

**Issue by romain130492** [pabloinsente/math-app-ml#1]
Hey
I simply made a black and white version of your `introduction to linear algebra`, it was easier to print it and read it properly, made be it can be usefull for other ? 
[Introduction to Linear Algebra for Applied Machine Learning with Python smaller.pdf](https://github.com/pabloinsente/math-app-ml/files/4841754/Introduction.to.Linear.Algebra.for.Applied.Machine.Learning.with.Python.smaller.pdf)

Great introduction btw, thanks for that!

**Comment by pabloinsente** [comment]
Thanks! Looks great.
I created a white-background version of the Notebook in case you want to generate a PDF with the images with white backgrounds. I'll add the PDF to the repo.
https://github.com/pabloinsente/math-app-ml/blob/master/notebooks/01-linear-algebra/01-linear-algebra-white-background.ipynb
